// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservas.Infrastructure.Persistencia;

#nullable disable

namespace Reservas.Infrastructure.Migraciones
{
    [DbContext(typeof(ReservasDbContext))]
    partial class ReservasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservas.Domain.Reservas.NocheHabitacion", b =>
                {
                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Noche")
                        .HasColumnType("date");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HabitacionId", "Noche");

                    b.HasIndex("ReservaId");

                    b.ToTable("NochesHabitacion", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Reservas.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgenteEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Seq")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Seq"));

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("Reservas.Infrastructure.Idempotencia.MensajeProcesado", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId");

                    b.ToTable("MensajesProcesados", (string)null);
                });

            modelBuilder.Entity("Reservas.Infrastructure.Persistencia.OutboxMessage", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Seq"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ReclamadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Seq");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("Estado", "Seq");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Reservas.Infrastructure.Proyeccion.ProyeccionHabitacion", b =>
                {
                    b.Property<Guid>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal?>("CostoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Impuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VersionEstado")
                        .HasColumnType("int");

                    b.Property<int?>("VersionEstatico")
                        .HasColumnType("int");

                    b.Property<int>("VersionPrecio")
                        .HasColumnType("int");

                    b.HasKey("HabitacionId");

                    b.HasIndex("Ciudad");

                    b.ToTable("ProyeccionHabitacion", (string)null);
                });

            modelBuilder.Entity("Reservas.Infrastructure.Proyeccion.ProyeccionHotelEstado", b =>
                {
                    b.Property<Guid>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("VersionEstado")
                        .HasColumnType("int");

                    b.HasKey("HotelId");

                    b.ToTable("ProyeccionHotelEstado", (string)null);
                });

            modelBuilder.Entity("Reservas.Domain.Reservas.NocheHabitacion", b =>
                {
                    b.HasOne("Reservas.Domain.Reservas.Reserva", null)
                        .WithMany("Noches")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reservas.Domain.Reservas.Reserva", b =>
                {
                    b.OwnsOne("Reservas.Domain.Reservas.ContactoEmergencia", "ContactoEmergencia", b1 =>
                        {
                            b1.Property<Guid>("ReservaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("NombreCompleto")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ContactoNombreCompleto");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("ContactoTelefono");

                            b1.HasKey("ReservaId");

                            b1.ToTable("Reservas");

                            b1.WithOwner()
                                .HasForeignKey("ReservaId");
                        });

                    b.OwnsOne("Reservas.Domain.Reservas.Estancia", "Estancia", b1 =>
                        {
                            b1.Property<Guid>("ReservaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Entrada")
                                .HasColumnType("date")
                                .HasColumnName("Entrada");

                            b1.Property<DateOnly>("Salida")
                                .HasColumnType("date")
                                .HasColumnName("Salida");

                            b1.HasKey("ReservaId");

                            b1.ToTable("Reservas");

                            b1.WithOwner()
                                .HasForeignKey("ReservaId");
                        });

                    b.OwnsMany("Reservas.Domain.Reservas.Huesped", "Huespedes", b1 =>
                        {
                            b1.Property<Guid>("ReservaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Apellidos")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<DateOnly>("FechaNacimiento")
                                .HasColumnType("date");

                            b1.Property<string>("Genero")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<string>("Nombres")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.HasKey("ReservaId", "Id");

                            b1.ToTable("ReservaHuespedes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReservaId");

                            b1.OwnsOne("Reservas.Domain.Reservas.Documento", "Documento", b2 =>
                                {
                                    b2.Property<Guid>("HuespedReservaId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("HuespedId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasMaxLength(60)
                                        .HasColumnType("nvarchar(60)")
                                        .HasColumnName("DocumentoNumero");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasMaxLength(40)
                                        .HasColumnType("nvarchar(40)")
                                        .HasColumnName("DocumentoTipo");

                                    b2.HasKey("HuespedReservaId", "HuespedId");

                                    b2.ToTable("ReservaHuespedes");

                                    b2.WithOwner()
                                        .HasForeignKey("HuespedReservaId", "HuespedId");
                                });

                            b1.Navigation("Documento")
                                .IsRequired();
                        });

                    b.OwnsOne("Reservas.Domain.Reservas.SolicitudCancelacion", "SolicitudCancelacion", b1 =>
                        {
                            b1.Property<Guid>("ReservaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly?>("FechaResolucion")
                                .HasColumnType("date")
                                .HasColumnName("CancelacionFechaResolucion");

                            b1.Property<DateOnly>("FechaSolicitud")
                                .HasColumnType("date")
                                .HasColumnName("CancelacionFechaSolicitud");

                            b1.Property<string>("IniciadaPor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CancelacionIniciadaPor");

                            b1.Property<string>("MotivoCategoria")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("CancelacionMotivoCategoria");

                            b1.Property<string>("MotivoDetalle")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("CancelacionMotivoDetalle");

                            b1.Property<string>("MotivoResolucion")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("CancelacionMotivoResolucion");

                            b1.Property<decimal?>("PenalidadAplicadaPorcentaje")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("CancelacionPenalidadAplicadaPorcentaje");

                            b1.Property<bool>("PenalidadFueOverride")
                                .HasColumnType("bit")
                                .HasColumnName("CancelacionPenalidadFueOverride");

                            b1.Property<decimal>("PenalidadPorcentaje")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("CancelacionPenalidadPorcentaje");

                            b1.Property<string>("ResueltaPor")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("CancelacionResueltaPor");

                            b1.Property<string>("Resultado")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CancelacionResultado");

                            b1.HasKey("ReservaId");

                            b1.ToTable("Reservas");

                            b1.WithOwner()
                                .HasForeignKey("ReservaId");
                        });

                    b.Navigation("ContactoEmergencia");

                    b.Navigation("Estancia")
                        .IsRequired();

                    b.Navigation("Huespedes");

                    b.Navigation("SolicitudCancelacion");
                });

            modelBuilder.Entity("Reservas.Domain.Reservas.Reserva", b =>
                {
                    b.Navigation("Noches");
                });
#pragma warning restore 612, 618
        }
    }
}
